{{- $root := . -}}
{{- range .Values.customers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-{{ .name | lower | kebabcase }}
  labels:
    app: rsvp
    customer: {{ .name | lower | kebabcase }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsvp
      customer: {{ .name | lower | kebabcase }}
  template:
    metadata:
      labels:
        app: rsvp
        customer: {{ .name | lower | kebabcase }}
    spec:
      containers:
      - name: rsvp-app
        image: {{ $root.Values.image }}
        env:
        - name: MONGODB_HOST
          value: rsvp-db
        - name: MONGODB_DATABASE
          value: {{ .name | lower | kebabcase }}
        envFrom:
        - configMapRef:
            name: customer-config-{{ .name | lower | kebabcase }}-{{ toJson . | sha256sum }}
        ports:
        - containerPort: 5000
          name: web-port
---
apiVersion: v1
kind: Service
metadata:
  name: rsvp-{{ .name | lower | kebabcase }}
  labels:
    app: rsvp
    customer: {{ .name | lower | kebabcase }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    app: rsvp
    customer: {{ .name | lower | kebabcase }}
{{- end }}
