{{- range .Values.customers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-db-{{ .name | lower | kebabcase }}
  labels:
    appdb: rsvpdb
    customer: {{ .name | lower | kebabcase }}
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: rsvpdb
      customer: {{ .name | lower | kebabcase }}
  template:
    metadata:
      labels:
        appdb: rsvpdb
        customer: {{ .name | lower | kebabcase }}
    spec:
      containers:
      - name: rsvp-db
        image: mongo:3.3
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: rsvp-db-{{ .name | lower | kebabcase }}
  labels:
    app: rsvpdb
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    appdb: rsvpdb
    customer: {{ .name | lower | kebabcase }}
{{- end }}
